# Generated by Django 2.1 on 2019-10-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_id', models.IntegerField()),
                ('race_id', models.IntegerField()),
                ('arr_no', models.IntegerField()),
                ('horse_no', models.IntegerField()),
                ('horsename', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('jockey', models.CharField(max_length=10)),
                ('trainer', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('lasttime', models.FloatField()),
                ('odds', models.IntegerField()),
            ],
        ),
    ]
